### ISSUE TITLE
Dev release of XML::Parser is broken on CPAN

### ISSUE THREAD

**Issue by toddr** [chorny/XML-Parser#3]
I've released a dev version of XML::Parser on CPAN and am seeing alot of failures in the Free BSD camp. I'm assuming it's an incompatibility with expat on those boxes.

I _think_ this may be related to a new/old issue reported in RT - https://rt.cpan.org/Ticket/Display.html?id=55729

http://search.cpan.org/~toddr/XML-Parser-2.40_01/

http://www.cpantesters.org/distro/X/XML-Parser.html#XML-Parser-2.40?grade=1&perlmat=1&patches=1&oncpan=2&distmat=3&perlver=ALL&osname=ALL&version=2.40_01

I do not plan to release a prod version until we can figure this out.

**Comment by dsteinbrunner** [comment]
Can this be closed?

**Comment by toddr** [comment]
No. We've not turned off the TODO. I'm working that now.

**Comment by toddr** [comment]
Tests are converted to Test::More and we're going to see if Free BSD is fixed per:

http://www.freebsd.org/cgi/query-pr.cgi?pr=157469

**Comment by toddr** [comment]
2.41_01 uploaded to PAUSE for testing.
