### ISSUE TITLE
CPAN release at version 2.41, repo at 2.40_02

### ISSUE THREAD

**Issue by dsteinbrunner** [chorny/XML-Parser#6]
It seems some work was done outside of the repo to make the 2.41 release and those changes should be synced back into the repo.

**Comment by toddr** [comment]
Sorry for the confusion. I thought I had taken over this module. Sorry for not updating the history URL. It can be found here: https://github.com/toddr/XML-Parser

**Comment by chorny** [comment]
Todd, if you want to move official repository to https://github.com/toddr/XML-Parser, please merge all new commits that are in https://github.com/chorny/XML-Parser

**Comment by toddr** [comment]
It should be done as of yesterday. Release this weekend. Ill give you a direct commit bit on the repo if you like?

**Comment by chorny** [comment]
Yes, I'd like to have a commit bit - just found a bug.

**Comment by toddr** [comment]
You have access to https://github.com/toddr/XML-Parser as a collaborator.
