### ISSUE TITLE
Bundling expat.h and expat_external.h?

### ISSUE THREAD

**Issue by Hugmeir** [chorny/XML-Parser#7]
Howdy!

I was trying to build XML::Parser on android, and ran into a bit of an issue: While the OS does come with a libexpat.so, it doesn't ship any headers, so the build fails.
Merely wget'ing the headers and setting EXPATINCPATH=... makes the build work, but that sort of manual solution is kind of terrible; I was wondering if the module could bundle those headers and use them if there is a library, or alternatively, maybe make the module download the headers from the expat repo.

I can provide a pull request for either way, assuming one of those options is acceptable.

**Comment by hartwork** [comment]
The provider of libexpat.so should provide `expat.h` and `expat_external.h` that match the specific `.so` file provided, some way. If XML::Parser provided those files, it would need to keep their copies up to date. That's probably not in the best interest of the project. Article [Why not bundle dependencies](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies) would also apply to some extent for bundling headers. My vote for closing as "wont fix".

**Comment by toddr** [comment]
#include expat.h is found right here https://github.com/chorny/XML-Parser/blob/master/Expat/Expat.xs#L12

I agree. this is a won't fix.
